### ISSUE TITLE
The imports need to be fixed according to Golang's convention

### ISSUE THREAD

**Issue by hsluoyz** [fjballest/clive#1]
The imports in this project are like:

https://github.com/fjballest/clive/blob/bbd0190bca49d3c1d01df8b23d3f529b96d11438/cmd/ch/ch.go#L6-L12

The paths above like ``clive/cmd`` should be ``github.com/fjballest/clive/cmd``. And this is how the official ``go get`` command works. It puts the project into the ``$GOPATH/src/github.com/fjballest/clive`` instead of ``$GOPATH/src/clive``. Although you mentioned the following installation instructions in README, supporting ``go get`` and common importing convention is always a good thing.

```shell
mkdir $GOPATH/src
cd $GOPATH/src
git clone git://git.lsub.org/clive.git clive
```

I suggest all the imports can be fixed.

**Comment by fjballest** [comment]
clive does not use std go.
